---
title: "Writing functions in Shiny 1"
author: "David Jarrett"
date: "05/08/2020"
output: html_document
---

This document gives a simple example of how to improve Shiny code. This is how I would write out a bunch sliders going from 0 to 1 in an app:

```{r ui code}
library(shiny)
ui <- fluidRow(
  sliderInput("alpha", "alpha", min = 0, max = 1, value = 0.5, step = 0.1),
  sliderInput("beta",  "beta",  min = 0, max = 1, value = 0.5, step = 0.1),
  sliderInput("gamma", "gamma", min = 0, max = 1, value = 0.5, step = 0.1),
  sliderInput("delta", "delta", min = 0, max = 1, value = 0.5, step = 0.1)
)
```

But actually it's unnecessary to duplicated the code, we can use a function like this. We specify the parameters of the function once in the first bit of code, then specify the names.

```{r function}
sliderInput01 <- function(id) {
  sliderInput(id, label = id, min = 0, max = 1, value = 0.5, step = 0.1)
}

ui <- fluidRow(
  sliderInput01("alpha"),
  sliderInput01("beta"),
  sliderInput01("gamma"),
  sliderInput01("delta")
)
```